name: user_resort_booking_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  image_picker: ^1.1.2
  flutter_bloc: ^8.1.6
  google_fonts: ^6.2.1
  go_router: ^14.6.2
  font_awesome_flutter: ^10.8.0
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  freezed_annotation: ^2.4.4
  cloud_firestore: ^5.5.1
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.1.1
  google_sign_in: ^6.2.2
  file_picker: ^8.1.7
  carousel_slider: ^5.0.0
  google_maps_flutter: ^2.10.0
  geocode: ^1.0.3
  location: ^6.0.2
  http: ^1.2.2
  flutter_polyline_points: ^2.1.0
  razorpay_flutter: ^1.3.7
  intl: ^0.20.1
  syncfusion_flutter_datepicker: ^28.1.39
  shimmer: ^3.0.0
  permission_handler: ^11.3.1
  firebase_messaging: ^15.2.1
  flutter_rating: ^2.0.2
  flutter_local_notifications: ^18.0.1
  collection: ^1.19.0
  webview_flutter: ^4.10.0
  flutter_html: ^3.0.0-beta.2
  shared_preferences: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  build_runner: ^2.4.14
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/